window.LOVE_STORY = {
  togetherDays: 495,
  secretMessage: {
    title: "你发现了一个小秘密 ✨",
    body: "我不是在最好的时光遇见了你，而是遇见了你，才有了最好的时光。每一次心跳，都在叫你的名字。",
    closeLabel: "藏进心里",
  },
  photos: [
    { src: "image/1.jpg", title: "记忆 01" },
    { src: "image/2.jpg", title: "记忆 02" },
    { src: "image/3.jpg", title: "记忆 03" },
    { src: "image/4.jpg", title: "记忆 04" },
    { src: "image/5.jpg", title: "记忆 05" },
    { src: "image/6.jpg", title: "记忆 06" },
    { src: "image/7.jpg", title: "记忆 07" },
    { src: "image/8.jpg", title: "记忆 08" },
    { src: "image/9.jpg", title: "记忆 09" },
    { src: "image/10.jpg", title: "记忆 10" },
    { src: "image/11.jpg", title: "记忆 11" },
    { src: "image/12.jpg", title: "记忆 12" },
  ],
  timeline: [
    {
      date: "记忆 01",
      title: "第一次一起过生日",
      text: "宝宝第一次和我们过生日。当时我才大一。",
      photo: { src: "image/1.jpg", title: "第一次一起过生日" },
    },
    {
      date: "记忆 02",
      title: "一起过万圣节",
      text: "宝宝和我一起过万圣节，好开心。",
      photo: { src: "image/2.jpg", title: "一起过万圣节" },
    },
    {
      date: "记忆 03",
      title: "寒假前的咖喱饭",
      text: "蓝蓝寒假前和宝宝一起吃咖喱饭。",
      photo: { src: "image/3.jpg", title: "寒假前的咖喱饭" },
    },
    {
      date: "记忆 04",
      title: "寒假里的视频电话",
      text: "宝宝寒假的时候和我打视频电话，真好。",
      photo: { src: "image/4.jpg", title: "寒假里的视频电话" },
    },
    {
      date: "记忆 05",
      title: "妹妹镜头里的宝宝",
      text: "宝宝的妹妹拍的照片。",
      photo: { src: "image/5.jpg", title: "妹妹镜头里的宝宝" },
    },
    {
      date: "记忆 06",
      title: "我们在一起啦",
      text: "我们在一起啦啦啦。",
      photo: { src: "image/6.jpg", title: "我们在一起啦" },
    },
    {
      date: "记忆 07",
      title: "正式在一起的那天",
      text: "正式在一起那天。",
      photo: { src: "image/7.jpg", title: "正式在一起的那天" },
    },
    {
      date: "记忆 08",
      title: "图书馆里的小小 U",
      text: "软软考研在图书馆用小小u哄我。",
      photo: { src: "image/8.jpg", title: "图书馆里的小小 U" },
    },
    {
      date: "记忆 09",
      title: "暑假前的小便利贴",
      text: "暑假前软软给我小便利贴。",
      photo: { src: "image/9.jpg", title: "暑假前的小便利贴" },
    },
    {
      date: "记忆 10",
      title: "送宝宝去考研",
      text: "送宝宝去考研考场，那天我在外面看了背影很久。",
      photo: { src: "image/10.jpg", title: "送宝宝去考研" },
    },
    {
      date: "记忆 11",
      title: "宝宝送我去实习",
      text: "宝宝送我去实习。",
      photo: { src: "image/11.jpg", title: "宝宝送我去实习" },
    },
    {
      date: "记忆 12",
      title: "六一儿童节",
      text: "六一儿童节吃海底捞~",
      photo: { src: "image/12.jpg", title: "六一儿童节" },
    },
  ],
  captions: [
    ["所有偶然", "都是命中注定的必然"],
    ["世界很大", "但我总会走向你"],
    ["时间绕成环", "最后还是回到我们"],
    ["把每张照片", "都交给这一场光影"],
    ["你一笑", "我的世界就亮了"],
    ["不是喜欢", "是偏爱，是例外，是首选"],
    ["星河滚烫", "你是人间理想"],
    ["来日方长", "我想和你慢慢走"],
  ],
  characters: {
    kitty: {
      name: "Hello Kitty",
      color: "#ff3b6e",
      accent: "#ffffff",
      glow: "#ff85a2",
      symbol: "❀",
      particles: ["❀", "♥", "✿", "♡", "✧"],
    },
    cinnamoroll: {
      name: "大耳狗",
      color: "#7ec8e3",
      accent: "#ffffff",
      glow: "#b8e4f0",
      symbol: "☁",
      particles: ["☁", "♡", "✧", "·", "♥"],
    },
    kuromi: {
      name: "库洛米",
      color: "#b57edc",
      accent: "#2d1b3d",
      glow: "#d4a5f0",
      symbol: "✦",
      particles: ["✦", "♡", "★", "✧", "♥"],
    },
    melody: {
      name: "美乐蒂",
      color: "#ff7096",
      accent: "#ffd0dc",
      glow: "#ffb3c6",
      symbol: "✿",
      particles: ["✿", "♥", "❀", "♡", "✧"],
    },
  },
  defaultCharacter: "kitty",
  letterMessage: {
    greeting: "亲爱的宝宝：",
    body: [
      "从我们认识的那天起，我的世界就变得不一样了。以前总觉得喜欢是很简单的事，直到遇见你，才发现原来喜欢一个人可以这么深、这么满。",
      "我们一起走过了这么多日子，每一个和你在一起的瞬间，我都悄悄收藏在心里。你笑的时候，眼睛弯成月牙；你认真的时候，眉头微微皱起；你靠在我肩膀上的时候，时间好像都变慢了。",
      "我想和你一起看更多的风景，一起经历更多的人生。不管未来会怎样，只要你在身边，我就有勇气面对一切。",
      "生日快乐，我的女孩。",
      "希望以后的每一个生日，我都能陪在你身边。"
    ],
    sign: "—— 永远爱你的我"
  }
};
